In [24]:
# ============================================================
# STEP 1 — IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import joblib
import json

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

print("=" * 70)
print("SMARTPLAY MODEL DEPLOYMENT")
print("=" * 70)

print("✓ Libraries loaded successfully.")

======================================================================
SMARTPLAY MODEL DEPLOYMENT
======================================================================
✓ Libraries loaded successfully.

In [25]:
# ============================================================
# STEP 2 — DEFINE PROJECT PATHS
# ============================================================

BASE_PATH = Path("..")

DATA_PATH = BASE_PATH / "data" / "processed"
MODEL_PATH = BASE_PATH / "models"
DEPLOYMENT_PATH = BASE_PATH / "deployment"

DEPLOYMENT_PATH.mkdir(
    parents=True,
    exist_ok=True
)

print("=" * 70)
print("PROJECT PATH CONFIGURATION")
print("=" * 70)

print("Data path      :", DATA_PATH.resolve())
print("Model path     :", MODEL_PATH.resolve())
print("Deployment path:", DEPLOYMENT_PATH.resolve())

print("\n✓ Paths configured successfully.")

======================================================================
PROJECT PATH CONFIGURATION
======================================================================
Data path      : /Users/aathilhakam/Desktop/Research/An-AI-Driven-Teacher-Assisted-Learning-System/SmartPlay-AI-Recommendation/data/processed
Model path     : /Users/aathilhakam/Desktop/Research/An-AI-Driven-Teacher-Assisted-Learning-System/SmartPlay-AI-Recommendation/models
Deployment path: /Users/aathilhakam/Desktop/Research/An-AI-Driven-Teacher-Assisted-Learning-System/SmartPlay-AI-Recommendation/deployment

✓ Paths configured successfully.

In [26]:
# ============================================================
# STEP 3 — CHECK REQUIRED FILES
# ============================================================

required_files = {

    "Student Features":
        DATA_PATH / "student_features.csv",

    "Validated Learning Paths":
        DATA_PATH / "validated_personalized_learning_paths.csv",

    "Student Learning Summary":
        DATA_PATH / "student_learning_path_summary.csv",

    "Random Forest":
        MODEL_PATH / "random_forest.joblib",

    "Decision Tree":
        MODEL_PATH / "decision_tree.joblib",

    "Logistic Regression":
        MODEL_PATH / "logistic_regression.joblib"
}


print("=" * 70)
print("REQUIRED FILE VERIFICATION")
print("=" * 70)


missing_files = []


for name, file_path in required_files.items():

    if file_path.exists():

        print(f"✓ {name}: {file_path}")

    else:

        print(f"✗ {name}: NOT FOUND")
        missing_files.append(str(file_path))


if len(missing_files) == 0:

    print("\n✓ All deployment files are available.")

else:

    print("\n⚠ Missing files:")

    for file in missing_files:
        print(" -", file)

======================================================================
REQUIRED FILE VERIFICATION
======================================================================
✓ Student Features: ../data/processed/student_features.csv
✓ Validated Learning Paths: ../data/processed/validated_personalized_learning_paths.csv
✓ Student Learning Summary: ../data/processed/student_learning_path_summary.csv
✓ Random Forest: ../models/random_forest.joblib
✓ Decision Tree: ../models/decision_tree.joblib
✓ Logistic Regression: ../models/logistic_regression.joblib

✓ All deployment files are available.

In [27]:
# ============================================================
# STEP 4 — LOAD DEPLOYMENT DATA
# ============================================================

print("=" * 70)
print("LOADING DEPLOYMENT DATA")
print("=" * 70)


student_features = pd.read_csv(
    DATA_PATH / "student_features.csv"
)


validated_learning_path = pd.read_csv(
    DATA_PATH /
    "validated_personalized_learning_paths.csv"
)


student_summary = pd.read_csv(
    DATA_PATH /
    "student_learning_path_summary.csv"
)


print(
    "Student features shape:",
    student_features.shape
)

print(
    "Validated learning path shape:",
    validated_learning_path.shape
)

print(
    "Student summary shape:",
    student_summary.shape
)


print("\n✓ Deployment datasets loaded successfully.")

======================================================================
LOADING DEPLOYMENT DATA
======================================================================
Student features shape: (15, 29)
Validated learning path shape: (30, 22)
Student summary shape: (15, 6)

✓ Deployment datasets loaded successfully.

In [28]:
# ============================================================
# STEP 5 — VERIFY DEPLOYMENT DATA
# ============================================================

print("=" * 70)
print("STEP 5 — VERIFY DEPLOYMENT DATA")
print("=" * 70)


print("\nStudent features shape:")
print(student_features.shape)


print(
    "\nNumber of students:",
    student_features["Student_ID"].nunique()
)


print(
    "\nValidated learning path shape:",
    validated_learning_path.shape
)


print(
    "Number of learning-path students:",
    validated_learning_path[
        "Student_ID"
    ].nunique()
)


print(
    "Number of learning-path records:",
    len(validated_learning_path)
)


print(
    "Number of unique recommended lessons:",
    validated_learning_path[
        "Recommended_Lesson_ID"
    ].nunique()
)


print(
    "\nStudent summary shape:",
    student_summary.shape
)


print("\n✓ Deployment data verified successfully.")

======================================================================
STEP 5 — VERIFY DEPLOYMENT DATA
======================================================================

Student features shape:
(15, 29)

Number of students: 15

Validated learning path shape: (30, 22)
Number of learning-path students: 15
Number of learning-path records: 30
Number of unique recommended lessons: 12

Student summary shape: (15, 6)

✓ Deployment data verified successfully.

In [29]:
# ============================================================
# STEP 6 — LOAD TRAINED MODELS
# ============================================================

import joblib

print("=" * 70)
print("STEP 6 — LOAD TRAINED MODELS")
print("=" * 70)


random_forest = joblib.load(
    MODEL_PATH / "random_forest.joblib"
)


decision_tree = joblib.load(
    MODEL_PATH / "decision_tree.joblib"
)


logistic_regression = joblib.load(
    MODEL_PATH / "logistic_regression.joblib"
)


models = {

    "Random Forest":
        random_forest,

    "Decision Tree":
        decision_tree,

    "Logistic Regression":
        logistic_regression

}


for name, model in models.items():

    print(
        f"✓ {name}: "
        f"{type(model).__name__}"
    )


print(
    "\n✓ All trained models loaded successfully."
)

======================================================================
STEP 6 — LOAD TRAINED MODELS
======================================================================
✓ Random Forest: Pipeline
✓ Decision Tree: Pipeline
✓ Logistic Regression: Pipeline

✓ All trained models loaded successfully.

In [30]:
# ============================================================
# STEP 7 — VERIFY MODEL STRUCTURE
# ============================================================

print("=" * 70)
print("STEP 7 — VERIFY MODEL STRUCTURE")
print("=" * 70)


for model_name, model in models.items():

    print("\n" + "-" * 70)
    print("Model:", model_name)
    print("-" * 70)


    if hasattr(
        model,
        "n_features_in_"
    ):

        print(
            "Input features:",
            model.n_features_in_
        )

    else:

        print(
            "Input features: Not available"
        )


    if hasattr(
        model,
        "feature_names_in_"
    ):

        print(
            "\nFeature names:"
        )

        print(
            list(
                model.feature_names_in_
            )
        )

    else:

        print(
            "\nFeature names: "
            "Not stored in model"
        )


    if hasattr(
        model,
        "classes_"
    ):

        print(
            "\nOutput classes:"
        )

        print(
            list(
                model.classes_
            )
        )


print(
    "\n✓ Model structure verification completed."
)

======================================================================
STEP 7 — VERIFY MODEL STRUCTURE
======================================================================

----------------------------------------------------------------------
Model: Random Forest
----------------------------------------------------------------------
Input features: 28

Feature names:
['Average_Score', 'Average_Attempts', 'Average_Time_Taken', 'Total_Activities', 'Completion_Rate', 'Pre_Test', 'Post_Test', 'Unit_Test', 'Monthly_Test', 'Term_Result', 'Motor_Skills_Score', 'Creativity_Score', 'Interactive_Engagement', 'Test_Improvement', 'Participation', 'Attention_Level', 'Confidence', 'Collaboration', 'Learning_Difficulty', 'Learning_Style', 'Participation_Score', 'Attention_Score', 'Confidence_Score', 'Collaboration_Score', 'Historical_Lessons', 'Average_Sequence_No', 'Completed_Historical_Lessons', 'Historical_Completion_Rate']

Output classes:
['Needs Practice', 'Successful', 'Waiting']

----------------------------------------------------------------------
Model: Decision Tree
----------------------------------------------------------------------
Input features: 28

Feature names:
['Average_Score', 'Average_Attempts', 'Average_Time_Taken', 'Total_Activities', 'Completion_Rate', 'Pre_Test', 'Post_Test', 'Unit_Test', 'Monthly_Test', 'Term_Result', 'Motor_Skills_Score', 'Creativity_Score', 'Interactive_Engagement', 'Test_Improvement', 'Participation', 'Attention_Level', 'Confidence', 'Collaboration', 'Learning_Difficulty', 'Learning_Style', 'Participation_Score', 'Attention_Score', 'Confidence_Score', 'Collaboration_Score', 'Historical_Lessons', 'Average_Sequence_No', 'Completed_Historical_Lessons', 'Historical_Completion_Rate']

Output classes:
['Needs Practice', 'Successful', 'Waiting']

----------------------------------------------------------------------
Model: Logistic Regression
----------------------------------------------------------------------
Input features: 28

Feature names:
['Average_Score', 'Average_Attempts', 'Average_Time_Taken', 'Total_Activities', 'Completion_Rate', 'Pre_Test', 'Post_Test', 'Unit_Test', 'Monthly_Test', 'Term_Result', 'Motor_Skills_Score', 'Creativity_Score', 'Interactive_Engagement', 'Test_Improvement', 'Participation', 'Attention_Level', 'Confidence', 'Collaboration', 'Learning_Difficulty', 'Learning_Style', 'Participation_Score', 'Attention_Score', 'Confidence_Score', 'Collaboration_Score', 'Historical_Lessons', 'Average_Sequence_No', 'Completed_Historical_Lessons', 'Historical_Completion_Rate']

Output classes:
['Needs Practice', 'Successful', 'Waiting']

✓ Model structure verification completed.

In [31]:
# ============================================================
# STEP 8 — VERIFY MODEL INPUT FEATURES
# ============================================================

print("=" * 70)
print("STEP 8 — VERIFY MODEL INPUT FEATURES")
print("=" * 70)


# ------------------------------------------------------------
# Get feature names expected by the production model
# ------------------------------------------------------------

production_model = random_forest


if not hasattr(
    production_model,
    "feature_names_in_"
):

    raise ValueError(
        "The trained model does not contain "
        "feature_names_in_."
    )


MODEL_FEATURES = list(
    production_model.feature_names_in_
)


print(
    "\nNumber of features expected by model:",
    len(MODEL_FEATURES)
)


print("\nExpected model features:")

for i, feature in enumerate(
    MODEL_FEATURES,
    start=1
):

    print(
        f"{i:02d}. {feature}"
    )


# ------------------------------------------------------------
# Check student feature dataset
# ------------------------------------------------------------

missing_features = [
    feature
    for feature in MODEL_FEATURES
    if feature not in student_features.columns
]


if len(missing_features) > 0:

    print("\n✗ Missing model features:")

    for feature in missing_features:
        print(" -", feature)

    raise ValueError(
        "Required model features are missing "
        "from student_features.csv."
    )


print(
    "\n✓ All required model features "
    "are available."
)


print(
    "\n✓ Model input compatibility verified."
)

======================================================================
STEP 8 — VERIFY MODEL INPUT FEATURES
======================================================================

Number of features expected by model: 28

Expected model features:
01. Average_Score
02. Average_Attempts
03. Average_Time_Taken
04. Total_Activities
05. Completion_Rate
06. Pre_Test
07. Post_Test
08. Unit_Test
09. Monthly_Test
10. Term_Result
11. Motor_Skills_Score
12. Creativity_Score
13. Interactive_Engagement
14. Test_Improvement
15. Participation
16. Attention_Level
17. Confidence
18. Collaboration
19. Learning_Difficulty
20. Learning_Style
21. Participation_Score
22. Attention_Score
23. Confidence_Score
24. Collaboration_Score
25. Historical_Lessons
26. Average_Sequence_No
27. Completed_Historical_Lessons
28. Historical_Completion_Rate

✓ All required model features are available.

✓ Model input compatibility verified.

In [32]:
# ============================================================
# STEP 9 — PREPARE MODEL INPUT
# ============================================================

print("=" * 70)
print("STEP 9 — PREPARE MODEL INPUT")
print("=" * 70)


# ------------------------------------------------------------
# Select exactly the features used during training
# ------------------------------------------------------------

X_deployment = student_features[
    MODEL_FEATURES
].copy()


print(
    "Deployment input shape:",
    X_deployment.shape
)


print(
    "Expected feature count:",
    len(MODEL_FEATURES)
)


print(
    "Actual feature count:",
    X_deployment.shape[1]
)


# ------------------------------------------------------------
# Check missing values
# ------------------------------------------------------------

missing_values = (
    X_deployment
    .isnull()
    .sum()
)


total_missing = (
    missing_values.sum()
)


print(
    "\nTotal missing values:",
    total_missing
)


if total_missing > 0:

    print(
        "\nColumns containing missing values:"
    )

    print(
        missing_values[
            missing_values > 0
        ]
    )

else:

    print(
        "✓ No missing values in model input."
    )


# ------------------------------------------------------------
# Final shape validation
# ------------------------------------------------------------

if X_deployment.shape[1] != len(
    MODEL_FEATURES
):

    raise ValueError(
        "Model input feature count does not match."
    )


print(
    "\n✓ Deployment input prepared successfully."
)

======================================================================
STEP 9 — PREPARE MODEL INPUT
======================================================================
Deployment input shape: (15, 28)
Expected feature count: 28
Actual feature count: 28

Total missing values: 0
✓ No missing values in model input.

✓ Deployment input prepared successfully.

In [33]:
# ============================================================
# STEP 10 — GENERATE MODEL PREDICTIONS
# ============================================================

print("=" * 70)
print("STEP 10 — GENERATE MODEL PREDICTIONS")
print("=" * 70)


prediction_results = pd.DataFrame({
    "Student_ID":
        student_features["Student_ID"]
})


# ------------------------------------------------------------
# Generate predictions from each trained model
# ------------------------------------------------------------

for model_name, model in models.items():

    prediction_column = (
        model_name.replace(" ", "_")
        + "_Prediction"
    )

    prediction_results[
        prediction_column
    ] = model.predict(
        X_deployment
    )


# ------------------------------------------------------------
# Display predictions
# ------------------------------------------------------------

print("\nPrediction results:")

display(
    prediction_results
)


print(
    "\n✓ Predictions generated successfully."
)

======================================================================
STEP 10 — GENERATE MODEL PREDICTIONS
======================================================================

Prediction results:

   Student_ID Random_Forest_Prediction Decision_Tree_Prediction Logistic_Regression_Prediction
0       ST001               Successful               Successful                     Successful
1       ST002               Successful               Successful                     Successful
2       ST003               Successful               Successful                     Successful
3       ST004                  Waiting                  Waiting                        Waiting
4       ST005               Successful               Successful                     Successful
5       ST006           Needs Practice           Needs Practice                 Needs Practice
6       ST007           Needs Practice           Needs Practice                 Needs Practice
7       ST008               Successful               Successful                     Successful
8       ST009           Needs Practice           Needs Practice                 Needs Practice
9       ST010               Successful               Successful                     Successful
10      ST011           Needs Practice           Needs Practice                 Needs Practice
11      ST012               Successful               Successful                     Successful
12      ST013               Successful               Successful                     Successful
13      ST014               Successful               Successful                     Successful
14      ST015           Needs Practice           Needs Practice                 Needs Practice

✓ Predictions generated successfully.

In [34]:
# ============================================================
# STEP 11 — SELECT PRODUCTION MODEL
# ============================================================

print("=" * 70)
print("STEP 11 — SELECT PRODUCTION MODEL")
print("=" * 70)


# Random Forest was selected during model evaluation
production_model_name = "Random Forest"

production_model = models[
    production_model_name
]


print(
    "Production model:",
    production_model_name
)


print(
    "Model type:",
    type(production_model).__name__
)


print(
    "\n✓ Production model selected successfully."
)

======================================================================
STEP 11 — SELECT PRODUCTION MODEL
======================================================================
Production model: Random Forest
Model type: Pipeline

✓ Production model selected successfully.

In [35]:
# ============================================================
# STEP 12 — CREATE STUDENT PREDICTION FUNCTION
# ============================================================

print("=" * 70)
print("STEP 13 — STUDENT PREDICTION FUNCTION")
print("=" * 70)


def predict_student(student_id):

    # --------------------------------------------------------
    # Find student
    # --------------------------------------------------------

    student_row = student_features[
        student_features["Student_ID"]
        .astype(str)
        .str.strip()
        == str(student_id).strip()
    ]


    # --------------------------------------------------------
    # Student not found
    # --------------------------------------------------------

    if student_row.empty:

        return {
            "Student_ID": student_id,
            "Status": "Student not found"
        }


    # --------------------------------------------------------
    # Prepare model input
    # --------------------------------------------------------

    X_student = student_row[
        MODEL_FEATURES
    ]


    # --------------------------------------------------------
    # Generate prediction
    # --------------------------------------------------------

    prediction = production_model.predict(
        X_student
    )[0]


    # --------------------------------------------------------
    # Generate probability if available
    # --------------------------------------------------------

    result = {

        "Student_ID":
            student_id,

        "Predicted_Outcome":
            prediction,

        "Model":
            production_model_name
    }


    if hasattr(
        production_model,
        "predict_proba"
    ):

        probabilities = (
            production_model
            .predict_proba(X_student)[0]
        )

        classes = (
            production_model
            .classes_
        )


        probability_dict = {
            str(cls):
            round(float(prob), 4)

            for cls, prob
            in zip(
                classes,
                probabilities
            )
        }


        result[
            "Prediction_Probabilities"
        ] = probability_dict


    return result


print(
    "✓ Student prediction function created."
)

======================================================================
STEP 13 — STUDENT PREDICTION FUNCTION
======================================================================
✓ Student prediction function created.

In [36]:
# ============================================================
# STEP 13 — TEST STUDENT PREDICTION
# ============================================================

print("=" * 70)
print("STEP 13  — TEST STUDENT PREDICTION")
print("=" * 70)


test_student_id = "ST001"


student_prediction = predict_student(
    test_student_id
)


print("\nStudent prediction:")

print(
    json.dumps(
        student_prediction,
        indent=4
    )
)

======================================================================
STEP 13  — TEST STUDENT PREDICTION
======================================================================

Student prediction:
{
    "Student_ID": "ST001",
    "Predicted_Outcome": "Successful",
    "Model": "Random Forest",
    "Prediction_Probabilities": {
        "Needs Practice": 0.05,
        "Successful": 0.95,
        "Waiting": 0.0
    }
}

In [37]:
# ============================================================
# STEP 14 — CREATE LEARNING PATH FUNCTION
# ============================================================

print("=" * 70)
print("STEP 14 — LEARNING PATH RETRIEVAL FUNCTION")
print("=" * 70)


def get_student_learning_path(
    student_id
):

    # --------------------------------------------------------
    # Find student's learning path
    # --------------------------------------------------------

    student_path = (
        validated_learning_path[
            validated_learning_path["Student_ID"]
            .astype(str)
            .str.strip()
            ==
            str(student_id).strip()
        ]
        .copy()
    )


    # --------------------------------------------------------
    # Student not found
    # --------------------------------------------------------

    if student_path.empty:

        return None


    # --------------------------------------------------------
    # Sort by learning path order
    # --------------------------------------------------------

    if "Path_Order" in student_path.columns:

        student_path = (
            student_path
            .sort_values(
                "Path_Order"
            )
        )


    return student_path


print(
    "✓ Learning path retrieval function created."
)

======================================================================
STEP 14 — LEARNING PATH RETRIEVAL FUNCTION
======================================================================
✓ Learning path retrieval function created.

In [38]:
# ============================================================
# STEP 15 — COMPLETE STUDENT RECOMMENDATION
# ============================================================

print("=" * 70)
print("STEP 15 — COMPLETE STUDENT RECOMMENDATION")
print("=" * 70)


def get_student_recommendation(
    student_id
):

    # --------------------------------------------------------
    # 1. Get prediction
    # --------------------------------------------------------

    prediction = predict_student(
        student_id
    )


    if prediction.get("Status") == \
            "Student not found":

        return {
            "Student_ID":
                student_id,

            "Status":
                "Student not found"
        }


    # --------------------------------------------------------
    # 2. Get personalized learning path
    # --------------------------------------------------------

    learning_path = (
        get_student_learning_path(
            student_id
        )
    )


    if learning_path is None:

        return {
            **prediction,

            "Status":
                "Prediction available, "
                "but learning path not found"
        }


    # --------------------------------------------------------
    # 3. Convert learning path to records
    # --------------------------------------------------------

    recommendations = (
        learning_path[
            [
                "Path_Order",
                "Learning_Stage",
                "Recommended_Lesson_ID",
                "Recommended_Subject",
                "Recommended_Topic",
                "Recommended_Competency",
                "Learning_Objective",
                "Difficulty_Level",
                "Required_Skills",
                "Classroom_Activities",
                "Alignment_Score",
                "Performance_Level",
                "Overall_Performance",
                "Teaching_Strategy",
                "Recommended_Duration",
                "Teacher_Action"
            ]
        ]
        .to_dict(
            orient="records"
        )
    )


    # --------------------------------------------------------
    # 4. Return complete recommendation
    # --------------------------------------------------------

    result = {

        **prediction,

        "Status":
            "Recommendation available",

        "Number_of_Recommendations":
            len(recommendations),

        "Learning_Path":
            recommendations
    }


    return result


print(
    "✓ Complete recommendation function created."
)

======================================================================
STEP 15 — COMPLETE STUDENT RECOMMENDATION
======================================================================
✓ Complete recommendation function created.

In [39]:
# ============================================================
# STEP 16 — TEST COMPLETE RECOMMENDATION
# ============================================================

print("=" * 70)
print("STEP 16 — TEST COMPLETE RECOMMENDATION")
print("=" * 70)


test_student_id = "ST001"


recommendation = (
    get_student_recommendation(
        test_student_id
    )
)


print(
    json.dumps(
        recommendation,
        indent=4,
        default=str
    )
)

======================================================================
STEP 16 — TEST COMPLETE RECOMMENDATION
======================================================================
{
    "Student_ID": "ST001",
    "Predicted_Outcome": "Successful",
    "Model": "Random Forest",
    "Prediction_Probabilities": {
        "Needs Practice": 0.05,
        "Successful": 0.95,
        "Waiting": 0.0
    },
    "Status": "Recommendation available",
    "Number_of_Recommendations": 2,
    "Learning_Path": [
        {
            "Path_Order": 1,
            "Learning_Stage": "Immediate Support",
            "Recommended_Lesson_ID": "LES021",
            "Recommended_Subject": "Mathematics",
            "Recommended_Topic": "Number Recognition",
            "Recommended_Competency": "Number Sense",
            "Learning_Objective": "Identify numbers 11-50 correctly",
            "Difficulty_Level": "Basic",
            "Required_Skills": "Number sequence knowledge",
            "Classroom_Activities": "Number chart activities",
            "Alignment_Score": 352.5,
            "Performance_Level": "Moderate",
            "Overall_Performance": 72.65,
            "Teaching_Strategy": "Structured Practice and Reinforcement",
            "Recommended_Duration": "20 minutes",
            "Teacher_Action": "Provide structured practice and monitor progress."
        },
        {
            "Path_Order": 2,
            "Learning_Stage": "Skill Development",
            "Recommended_Lesson_ID": "LES022",
            "Recommended_Subject": "English",
            "Recommended_Topic": "Simple Words",
            "Recommended_Competency": "Reading Skills",
            "Learning_Objective": "Read and identify simple CVC words",
            "Difficulty_Level": "Basic",
            "Required_Skills": "Phonics knowledge",
            "Classroom_Activities": "Word card exercises",
            "Alignment_Score": 174.47,
            "Performance_Level": "Moderate",
            "Overall_Performance": 72.65,
            "Teaching_Strategy": "Structured Practice and Reinforcement",
            "Recommended_Duration": "20 minutes",
            "Teacher_Action": "Provide structured practice and monitor progress."
        }
    ]
}

In [40]:
# ============================================================
# STEP 17 — TEST ALL STUDENTS
# ============================================================

print("=" * 70)
print("STEP 17 — TEST ALL STUDENTS")
print("=" * 70)


deployment_results = []


for student_id in (
    student_features["Student_ID"]
    .dropna()
    .unique()
):

    result = get_student_recommendation(
        student_id
    )


    deployment_results.append({

        "Student_ID":
            student_id,

        "Predicted_Outcome":
            result.get(
                "Predicted_Outcome"
            ),

        "Model":
            result.get(
                "Model"
            ),

        "Status":
            result.get(
                "Status"
            ),

        "Number_of_Recommendations":
            result.get(
                "Number_of_Recommendations",
                0
            )
    })


deployment_results_df = pd.DataFrame(
    deployment_results
)


print(
    "\nDeployment test results:"
)


display(
    deployment_results_df
)


print(
    "\nStudents tested:",
    len(deployment_results_df)
)


successful_tests = (
    deployment_results_df["Status"]
    == "Recommendation available"
).sum()


print(
    "Successful recommendation tests:",
    successful_tests
)


print(
    "Failed recommendation tests:",
    len(deployment_results_df)
    - successful_tests
)

======================================================================
STEP 17 — TEST ALL STUDENTS
======================================================================

Deployment test results:

   Student_ID Predicted_Outcome          Model                    Status  Number_of_Recommendations
0       ST001        Successful  Random Forest  Recommendation available                          2
1       ST002        Successful  Random Forest  Recommendation available                          2
2       ST003        Successful  Random Forest  Recommendation available                          2
3       ST004           Waiting  Random Forest  Recommendation available                          2
4       ST005        Successful  Random Forest  Recommendation available                          2
5       ST006    Needs Practice  Random Forest  Recommendation available                          2
6       ST007    Needs Practice  Random Forest  Recommendation available                          2
7       ST008        Successful  Random Forest  Recommendation available                          2
8       ST009    Needs Practice  Random Forest  Recommendation available                          2
9       ST010        Successful  Random Forest  Recommendation available                          2
10      ST011    Needs Practice  Random Forest  Recommendation available                          2
11      ST012        Successful  Random Forest  Recommendation available                          2
12      ST013        Successful  Random Forest  Recommendation available                          2
13      ST014        Successful  Random Forest  Recommendation available                          2
14      ST015    Needs Practice  Random Forest  Recommendation available                          2

Students tested: 15
Successful recommendation tests: 15
Failed recommendation tests: 0

In [41]:
# ============================================================
# STEP 18 — SAVE DEPLOYMENT RESULTS
# ============================================================

print("=" * 70)
print("STEP 18 — SAVE DEPLOYMENT RESULTS")
print("=" * 70)


deployment_results_file = (
    DEPLOYMENT_PATH
    / "deployment_test_results.csv"
)


deployment_results_df.to_csv(
    deployment_results_file,
    index=False
)


print(
    "Saved:",
    deployment_results_file
)


print(
    "\n✓ Deployment test results saved."
)

======================================================================
STEP 18 — SAVE DEPLOYMENT RESULTS
======================================================================
Saved: ../deployment/deployment_test_results.csv

✓ Deployment test results saved.

In [42]:
# ============================================================
# STEP 19 — FINAL DEPLOYMENT VALIDATION
# ============================================================

print("=" * 70)
print("FINAL DEPLOYMENT VALIDATION")
print("=" * 70)


checks = {

    "Models loaded":
        len(models) == 3,

    "Production model available":
        production_model is not None,

    "Model features verified":
        len(MODEL_FEATURES) == 28,

    "Student data available":
        len(student_features) > 0,

    "Learning paths available":
        len(validated_learning_path) > 0,

    "All students tested":
        len(deployment_results_df)
        ==
        student_features[
            "Student_ID"
        ].nunique(),

    "All recommendation tests passed":
        successful_tests
        ==
        len(deployment_results_df)
}


print()


for check_name, status in checks.items():

    symbol = "✓" if status else "✗"

    print(
        f"{symbol} {check_name}: {status}"
    )


all_checks_passed = all(
    checks.values()
)


print("\n" + "=" * 70)


if all_checks_passed:

    print(
        "✓ SMARTPLAY MODEL DEPLOYMENT VALIDATION PASSED"
    )

else:

    print(
        "✗ SMARTPLAY MODEL DEPLOYMENT VALIDATION FAILED"
    )


print("=" * 70)

======================================================================
FINAL DEPLOYMENT VALIDATION
======================================================================

✓ Models loaded: True
✓ Production model available: True
✓ Model features verified: True
✓ Student data available: True
✓ Learning paths available: True
✓ All students tested: True
✓ All recommendation tests passed: True

======================================================================
✓ SMARTPLAY MODEL DEPLOYMENT VALIDATION PASSED
======================================================================